#! /bin/bash

BEGIN {
    printf "Bill for the `date` \n"
    
    printf "---------------------------\n"
}

{
    total = $3 * $4
    recno = $1
    item = $2
    gtotal += total
    printf "%d %s Rs.%f\n", recno, item, total
    
}

END {
   printf "---------------------------\n"
   printf "Total Rs. %f\n" ,gtotal
   printf "===========================\n"
}

